apiVersion: v1
kind: Service
metadata:
  name: gregorian-api
  namespace: gregorian
spec:
  selector:
    app: gregorian-api
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
