apiVersion: apps/v1
kind: Deployment
metadata:
  name: gregorian-app
  namespace: gregorian
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gregorian-app
  template:
    metadata:
      labels:
        app: gregorian-app
    spec:
      containers:
      - name: gregorian-app
        image: guiflauzino18/gregorian-app:beta
        envFrom:
          - configMapRef:
              name: gregorian-config
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
