# Informações sensíveis que serão passadas via variáveis de ambientes
apiVersion: v1
kind: Secret
metadata:
  name: gregorian-secret
  namespace: gregorian
type: Opaque
data:
  MYSQL_PASSWORD: cGFzczEyMw==
  MYSQL_ROOT_PASSWORD: cGFzczEyMw== # para gerar o base64: echo -n 'pass123' | base64
  JWT_SECRET: c3lzYWRtaW4h # para gerar o base64: echo -n 'sysadmin!' | base64