version: '3'
services:
 gregorian-api:
  image: 719836617769.dkr.ecr.us-east-2.amazonaws.com/gregorian-api:latest
  build:
   context: ../
   dockerfile: deploy/Dockerfile
  environment:
   - MYSQL_IP=$MYSQL_IP
   - MYSQL_USERNAME=$MYSQL_USERNAME
   - MYSQL_PASSWORD=$MYSQL_PASSWORD
   - JWT_SECRET=$JWT_SECRET
  
  ports:
   - 8080:8080

  network_mode: "host"
  volumes:
   - vol-gregorian:/gregorian

volumes:
 vol-gregorian:
