version: '3'
services:
 gregorian-api:
  image: gregorian-api:beta
  build:
   context: ../
   dockerfile: deploy/Dockerfile
  environment:
   - MYSQL_IP=$MYSQL_IP
   - MYSQL_USERNAME=$MYSQL_USERNAME
   - MYSQL_PASSWORD=$MYSQL_PASSWORD
   - JWT_SECRET=$JWT_SECRET
  
  ports:
   - 8080:8080

  network_mode: "host"
  volumes:
   - vol-gregorian:/gregorian

  restart: unless-stopped

volumes:
 vol-gregorian:
