name: Build da versão de Produção

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Extrair versão
              id: get_version
              run: |
                VERSION=$(grep -m1 '<version>' pom.xml | sed -E 's/.*<version>(.*)<\/version>.*/\1/')
                echo "Versão extraída: $VERSION"
                echo "VERSION=$VERSION" >> $GITHUB_ENV

            - name: Login no Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build da imagem Docker
              run: |
                docker build -t guiflauzino18/gregorian-api:${{ env.VERSION }} -f deploy/Prod/Dockerfile .
    
            - name: Push da imagem para o Docker Hub
              run: |
                docker push guiflauzino18/gregorian-api:${{ env.VERSION }}
    
            - name: Atualizar a tag "latest"
              run: |
                docker tag guiflauzino18/gregorian-api:${{ env.VERSION }} guiflauzino18/gregorian-api:latest
                docker push guiflauzino18/gregorian-api:latest