name: Deploy Production

on:
    push:
        branches:
            - prod

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{secrets.AWS_ROLE_ARN}}
                role-session-name: GitHub_Actions_Deploy_API_Production
                aws-region: ${{secrets.AWS_REGION}}

            - name: Login DOcker no ECR e criação das variaveis de ambiente
              run: |
                aws ecr get-login-password --region ${{secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com &&
                export MYSQL_IP=${{secrets.MYSQL_IP}} &&
                export MYSQL_USERNAME=${{secrets.MYSQL_USERNAME}} &&
                export MYSQL_PASSWORD=${{secrets.MYSQL_PASSWORD}} &&
                export JWT_SECRET=${{secrets.JWT_SECRET}}

            - name: Build e Push da Imagem para o ECR
              run: |
                cd build/
                docker build -t gregorian-api:latest .
                docker tag gregorian-api:latest ${{secrets.AWS_ACCOUNT_ID}}dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com/gregorian-api:latest
                docker push ${{secrets.AWS_ACCOUNT_ID}}dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com/gregorian-api:latest

            - name: Encerra instâncias em execução.
              run: |
                INSTANCE_IDS=$(aws ec2 describe-instances --filters "Name=tag:Resource,Values=gregorian-template" "Name=instance-state-name,Values=running" --query "Reservations[*].Instances[*].InstanceId" --output text)
                if [ -n "$INSTANCE_IDS" ]; then
                    aws ec2 stop-instances --instance-ids $INSTANCE_IDS
                    echo "Instâncias em execução encerradas: $INSTANCE_IDS"
                else
                    echo "Nenhuma instância em execução encontrada para encerrar."
                fi



